### PR TITLE
Update TravellingRuby extensions

### PR DESCRIPTION
**Pull request by ianks**
cc: @FooBarWidget

This updates the native extensions needed and puts the extensions in the correct location. I tested it and things seem to be working (on OSX at least). This should be one of the final steps before creating the Homebrew/Debian packages. :)

### CODE REVIEW

**Comment by FooBarWidget** [comment]
Please wait until the next Traveling Ruby release. I've discovered some issues with the way rugged and charlock_holmes are compiled, which the next release fixes.

**Comment by ianks** [comment]
Sounds good.

**Comment by ianks** [comment]
Also @FooBarWidget it looks like Rugged 0.22.0b4 is listed in GitHub Linguist. Although I think 0.22.0b5 theoretically should be compatible.

https://github.com/github/linguist/blob/master/github-linguist.gemspec#L19

**Comment by FooBarWidget** [comment]
Traveling Ruby 20150210 has been released.

**Pull request merged**
