### PR TITLE
Add deployment packaging task

### PR DESCRIPTION
**Pull request by ianks**
Thanks to @FooBarWidget for showing me the way of the [Traveling Ruby](http://phusion.github.io/traveling-ruby/). 

As of now the logic for building the packages is there. However, there are a few outstanding issues.

1. I have not tested the builds on Linux yet.
2. I have not decided on how/where to store the builds.
  - I want to have a history of all the builds for each version, so something like S3 sounds good for that. However, I want people to be able to install the HEAD from Github if they want to in Homebrew (eventually). This leads me to believe we might want to have some CI hook which maintains that. Although the trouble/value ratio on that might not be in my favor.

Please comment with any ideas/refactoring you see. Thanks!

### CODE REVIEW

**Comment by FooBarWidget** [comment]
Can't you host the builds on Github releases? Don't they support file attachments nowadays?

As for the Homebrew HEAD version: you can have the Homebrew recipe make a Traveling Ruby package.

**Comment by ianks** [comment]
@FooBarWidget Yeah I think I might end up doing with Github releases now that you mention it.

As for building the Traveling Ruby Package from HEAD, in the docs you mention there is a requirement for 2.1.x for bundle installing the Gems as that is what TR uses. Doesn't that kind of rule out building the package from HEAD?

**Comment by FooBarWidget** [comment]
That's right. But in your Homebrew recipe you could simply download Traveling Ruby and use *that* to run bundle install.

**Comment by FooBarWidget** [comment]
I think "Distrubution" should be "Distribution".

**Comment by ianks** [comment]
Thanks @FooBarWidget 

https://github.com/ianks/octodown/pull/45

**Pull request merged**
