### PR TITLE
Only pass links with href to relative_root_filter

### LINKED ISSUE #82: Fails for internal anchor tags
Internal anchor tags are used when you want a link to some other part of the same markdown file. For example:

example.md
```md
<a name="foo"></a>**Hello World**
...
[hello world](#foo)
```

When previewing this, clicking on the "hello world" link would take you to the "foo" anchor tag in the same file. However, it seems that having this in my markdown file makes `octodown` break.

Output when I run `octodown example.md`:

```sh
/Users/austinwood/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octodown-1.1.2/lib/octodown/support/relative_root_filter.rb:55:in `block in filter_links': undefined method `value' for nil:NilClass (NoMethodError)
```

### PR DESCRIPTION
**Pull request by monkbroc**
Was crashing for anchors (link tags without href). Fixes #82

I added the previously crashing markup to test.md

### CODE REVIEW

**Comment by ianks** [comment]
Thank you very much for your contribution? Do you mind writing a test to document this? Dont worry about the 2 failing tests, it seems Celluloid is acting up.

**Comment by monkbroc** [comment]
This was already caught by previous tests as long as the problematic markup was present in test.md. Since I added that markup to test.md in the future the tests would fail if this broke again.

**Comment by ianks** [comment]
Oh good to know. Thanks :+1:

**Comment by indiesquidge** [comment]
Awesome, thanks for the PR!

**Comment by monkbroc** [comment]
You're welcome, all

**Pull request merged**
